#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
# shows all processes, for all users, including those which might not have a TTY
# displays in a user-oriented format
# shows process hierarchy

ps -auxf
