#!/usr/bin/env bash
# This shell script prints "Best School" 10 times
# to the screen using a while loop, sand prints "Hi"
# after the ninth iteration

i=1
while [ $i -le 10 ];
do
	echo "Best School";
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
