#!/usr/bin/env bash
# this shell script print "Best School" 10 time
# prints 'bad luck' in place of the 4th iteration,
# prints 'good luck' in place of the 8th iteration

i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School";
	fi
	((i++))
done
